
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sys as sysdba
    password: 123456789
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
     multipart:
          max-file-size: 10GB
          max-request-size: 10GB